
export const SINAITICUS_BOOKS = [
    { name: "According to Matthew", id: "mat", section: "New Testament" },
    { name: "According to Mark", id: "mar", section: "New Testament" },
    { name: "According to Luke", id: "luk", section: "New Testament" },
    { name: "According to John", id: "joh", section: "New Testament" },
    { name: "Acts of the Apostles", id: "act", section: "New Testament" },
    { name: "Acts 29, Sonnini Manuscript", id: "act29", section: "Early Christian Writings" },
    { name: "Paul to the Romans", id: "rom", section: "New Testament" },
    { name: "Paul to the Corinthians 1st", id: "1co", section: "New Testament" },
    { name: "Paul to the Corinthians 2nd", id: "2co", section: "New Testament" },
    { name: "Paul to the Galatians", id: "gal", section: "New Testament" },
    { name: "Paul to the Ephesians", id: "eph", section: "New Testament" },
    { name: "Paul to the Philippians", id: "phi", section: "New Testament" },
    { name: "Paul to the Colossians", id: "col", section: "New Testament" },
    { name: "Paul to the Thessalonians 1st", id: "1th", section: "New Testament" },
    { name: "Paul to the Thessalonians 2nd", id: "2th", section: "New Testament" },
    { name: "Paul to Timothy 1st", id: "1ti", section: "New Testament" },
    { name: "Paul to Timothy 2nd", id: "2ti", section: "New Testament" },
    { name: "Paul to Titus", id: "tit", section: "New Testament" },
    { name: "Paul to Philemon", id: "phm", section: "New Testament" },
    { name: "Epistle of Hebrews", id: "heb", section: "New Testament" },
    { name: "Epistle of James", id: "jam", section: "New Testament" },
    { name: "Epistle of Peter 1st", id: "1pe", section: "New Testament" },
    { name: "Epistle of Peter 2nd", id: "2pe", section: "New Testament" },
    { name: "Epistle of John 1st", id: "1jo", section: "New Testament" },
    { name: "Epistle of John 2nd", id: "2jo", section: "New Testament" },
    { name: "Epistle of John 3rd", id: "3jo", section: "New Testament" },
    { name: "Epistle of Jude", id: "jud", section: "New Testament" },
    { name: "Revelation of Jesus Christ", id: "rev", section: "New Testament" },
    { name: "Epistle of Barnabas", id: "bar", section: "Early Christian Writings" },
    { name: "The Shepherd of Hermas", id: "her", section: "Early Christian Writings" },
    { name: "Didachē or Teaching of the Twelve", id: "did", section: "Early Christian Writings" },
];
